DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM ( --AS ENUM is a list of options that may be used by columns(which have this new type dept) in table rows
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

DROP TABLE IF EXISTS shopping_list;
CREATE TABLE IF NOT EXISTS shopping_list ( 
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, --creates id
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT 'f',
    category grocery NOT NULL
);

